version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/stories-facets
    steps:
      - checkout
      - attach_workspace:
          at: ~/stories-facets
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  publish:
    jobs:
      - publish #:
        # filters:
        #    branches:
        #      ignore: /.*/
        #    tags:
        #      only: /v[0-9]+(\.[0-9]+)*/

