version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/repo
    tags:
      only:
        - /v[0-9]+(\.[0-9]+)*/
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - run:
          name: Publish package
          command: npm publish --access public
